version: '3.9'

services:
  mediaverse-frontend:
    container_name: mediaverse-frontend
    image: tneskedev/mediaverse-frontend:latest
    ports:
    - '4201:80'
  mediaverse-backend:
    container_name: mediaverse-backend
    image: tneskedev/mediaverse-backend:latest
    ports:
      - '9756:81'
    env_file:
      - backend/.env
  mediaverse-db:
    container_name: mediaverse-db
    image: postgres:latest
    ports:
      - '5678:5432'
    volumes:
      - media-data:/var/lib/postgresql/data
    env_file:
      - backend/.env
volumes:
  media-data:
