spring:
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # löscht alles bei Neustart, später auf update andern
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        show_sql: false
server:
  port: 9756
  address: 0.0.0.0
app:
  offline:
    default:
      username: "off_user"
